# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'triangle.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 837)
        self.timer = QtCore.QTimer(MainWindow)
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.stepbystep)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputnodes = QtWidgets.QLineEdit(self.centralwidget)
        self.inputnodes.setGeometry(QtCore.QRect(480, 680, 113, 22))
        self.inputnodes.setObjectName("inputnodes")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(440, 720, 93, 28))
        self.add.setObjectName("add")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(540, 720, 93, 28))
        self.reset.setObjectName("reset")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 20, 811, 651))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.reset.clicked.connect(self.stepbystep)
        self.add.clicked.connect(self.draw)
        self.level_list = []
        self.start = 0
        self.end = 9999999
        self.steps = 0
        self.shortest_steps = []
        self.show_index = 0
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def printt(self):
        text = ""
        for level in self.level_list:
            for element in level:
                text+=element
            text+="\n"
        self.plainTextEdit.setPlainText(text)
    def draw(self):
        self.steps = 0
        self.plainTextEdit.clear()
        self.level_list = list()
        self.start = 0
        self.end = 9999999
        if self.inputnodes.text() == "": return
        n = int(self.inputnodes.text())
        for i in range(1, n + 1):
            self.level_list.append(["*"]*i)
            n -= 1
        self.printt()
    def errpopup(self, msg):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Error")
        msg.setWindowIcon(QtGui.QIcon("icon.png"))
        msg.setText(msg)
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        x = msg.exec_()
    def stepbystep(self):
        if not self.level_list: self.errpopup("Please Draw First!")
        if self.inputnodes.text() == "": return
        if self.plainTextEdit.toPlainText() == "": self.errpopup("Please Draw First!")
        if self.end == 9999999:
            self.end = len(self.level_list)-1
            self.timer.start()
        if len(self.level_list) % 2 != 0:
            if self.start == self.end:
                self.timer.stop()
                self.popup()
                return
            start_count = len(self.level_list[self.start])
            while len(self.level_list[self.start]) != len(self.level_list[self.end]):
                self.steps += 1
                self.level_list[self.start].append("*")
                self.printt()
            while len(self.level_list[self.end]) != start_count:
                self.level_list[self.end].remove("*")
                #self.steps += 1
                self.printt()
            self.start += 1
            self.end -= 1
        else:
            if self.end < self.start:
                self.timer.stop()
                self.popup()
                return
            start_count = len(self.level_list[self.start])
            while len(self.level_list[self.start]) != len(self.level_list[self.end]):
                self.level_list[self.start].append("*")
                self.steps += 1
                self.printt()
            while len(self.level_list[self.end]) != start_count:
                self.level_list[self.end].remove("*")
                self.shortest_steps.append(self.level_list)
                #self.steps += 1
                self.printt()
            self.start += 1
            self.end -= 1
    def popup(self):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Done")
        msg.setWindowIcon(QtGui.QIcon("icon.png"))
        msg.setText("Inverse Done!")
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.setInformativeText("Problem was solved in "+str(self.steps)+" steps!")
        x = msg.exec_()
        self.start = 0
        self.end = 9999999
        self.steps = 0
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Problem Solver"))
        self.add.setText(_translate("MainWindow", "Draw"))
        self.reset.setText(_translate("MainWindow", "Solve"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
